[pytest]
testpaths = tests
pythonpath = src
filterwarnings =
    ignore:Using .httpx. with .starlette.testclient. is deprecated
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
